/**
 * Project list. Every entry was loaded in a real browser to confirm it is live.
 *
 *   cat      filter key — see `projectCategories` in config.js
 *   label    small caption above the title (platform or project type)
 *   tools    comma-separated; shown as pills. Where the live site exposes its
 *            platform (WordPress, Shopify, MakeShop…) that is what is listed.
 *   image    screenshot of the live site; empty → generated placeholder
 *   shareUrl false → "Private" badge and no visit button (login-only systems)
 *
 * `name`, `label`, and `desc` may be { ja, en } objects (see ./i18n.js). Where a
 * company has no well-known Japanese name, `name` is a plain string used as-is
 * in both languages.
 */

const shot = (name) => `./images/work/${name}.jpg`;

export const projects = [
  /* ---------------------------------------------------------- Corporate */
  {
    name: { ja: '積水化学工業', en: 'Sekisui Chemical' },
    cat: 'corporate',
    label: { ja: 'コーポレートサイト', en: 'Corporate Site' },
    desc: {
      ja: '日本の大手メーカーのコーポレートサイト。企業情報、サステナビリティ、IR、製品、採用情報を掲載。',
      en: 'Corporate website for a major Japanese manufacturer, covering company information, sustainability, investor relations, products, and careers.',
    },
    tools: 'HTML/CSS, JavaScript, Responsive, IR Pages',
    image: shot('sekisui-co-jp'),
    liveUrl: 'https://www.sekisui.co.jp/',
    visitShort: 'sekisui.co.jp',
  },
  {
    name: { ja: '長島・大野・常松法律事務所', en: 'Nagashima Ohno & Tsunematsu' },
    cat: 'corporate',
    label: { ja: '法律事務所サイト', en: 'Law Firm Site' },
    desc: {
      ja: '日本を代表する総合法律事務所のウェブサイト。取扱分野、弁護士紹介、出版物を掲載。',
      en: 'Website for one of Japan’s leading full-service law firms, presenting practice areas, lawyer profiles, and publications.',
    },
    tools: 'WordPress, PHP, Vue.js',
    image: shot('noandt-com'),
    liveUrl: 'https://www.noandt.com/',
    visitShort: 'noandt.com',
  },
  {
    name: { ja: 'AZXプロフェッショナルズグループ', en: 'AZX Professionals Group' },
    cat: 'corporate',
    label: { ja: '士業グループサイト', en: 'Professional Firm Site' },
    desc: {
      ja: 'スタートアップに法務・特許・税務・会計・労務をワンストップで提供する専門家グループのサイト。',
      en: 'Site for a professional firm providing startups with one-stop legal, patent, tax, accounting, and labour services.',
    },
    tools: 'WordPress, PHP, jQuery',
    image: shot('azx-co-jp'),
    liveUrl: 'https://www.azx.co.jp/',
    visitShort: 'azx.co.jp',
  },
  {
    name: { ja: '大塚商会', en: 'Otsuka Shokai' },
    cat: 'corporate',
    label: { ja: 'ITソリューション', en: 'IT Solutions' },
    desc: {
      ja: 'システム販売、導入支援、教育、保守サービスを手がけるIT・オフィスシステム企業のウェブサイト。',
      en: 'Website for an IT and office-systems company covering system sales, implementation support, training, and maintenance services.',
    },
    tools: 'HTML/CSS, jQuery, Responsive',
    image: shot('otsuka-shokai-co-jp'),
    liveUrl: 'https://www.otsuka-shokai.co.jp/',
    visitShort: 'otsuka-shokai.co.jp',
  },
  {
    name: { ja: 'システムズナカシマ', en: 'Systems Nakashima' },
    cat: 'corporate',
    label: { ja: 'システム開発会社', en: 'System Developer' },
    desc: {
      ja: '岡山・東京・大阪に拠点を持つシステム開発会社のコーポレートサイト。受託開発、AI開発、CAD・SFAパッケージを紹介。',
      en: 'Corporate site for a system development company in Okayama, Tokyo, and Osaka offering custom systems, AI development, and packaged CAD and SFA software.',
    },
    tools: 'kintone, jQuery, HTML/CSS',
    image: shot('systems-nakashima-co-jp'),
    liveUrl: 'https://www.systems.nakashima.co.jp/',
    visitShort: 'systems.nakashima.co.jp',
  },
  {
    name: 'MIMIGURI',
    cat: 'corporate',
    label: { ja: 'コンサルティング会社', en: 'Consulting Firm' },
    desc: {
      ja: '人と組織を専門とする経営コンサルティング会社のウェブサイト。',
      en: 'Website for a management consulting firm specialising in people and organisations.',
    },
    tools: 'Next.js, React, TypeScript',
    image: shot('mimiguri-co-jp'),
    liveUrl: 'https://mimiguri.co.jp/',
    visitShort: 'mimiguri.co.jp',
  },
  {
    name: { ja: 'デジタルガレージ 採用サイト', en: 'Digital Garage Careers' },
    cat: 'corporate',
    label: { ja: '採用サイト', en: 'Recruiting Site' },
    desc: {
      ja: '中途・新卒・インターンの募集情報に加え、社員インタビュー、福利厚生、キャリアパスを掲載した採用サイト。',
      en: 'Recruiting site with mid-career, new-graduate, and internship listings, plus employee interviews, benefits, and career path information.',
    },
    tools: 'WordPress, PHP, Responsive',
    image: shot('recruit-garage-co-jp'),
    liveUrl: 'https://recruit.garage.co.jp/',
    visitShort: 'recruit.garage.co.jp',
  },
  {
    name: 'Leapy',
    cat: 'corporate',
    label: { ja: 'コーポレートサイト', en: 'Corporate Site' },
    desc: {
      ja: 'ウェブサイト制作、サイト運用、採用アウトソーシングを手がける岐阜の企業のコーポレートサイト。',
      en: 'Corporate site for a Gifu-based company offering website production, site operation, and recruitment outsourcing.',
    },
    tools: 'WordPress, PHP, jQuery',
    image: shot('leapy-jp'),
    liveUrl: 'https://leapy.jp/',
    visitShort: 'leapy.jp',
  },
  {
    name: { ja: 'アーツセンターあきた', en: 'Arts Center Akita' },
    cat: 'corporate',
    label: { ja: '文化芸術団体', en: 'Arts Organisation' },
    desc: {
      ja: '秋田のアーツセンターのウェブサイト。地域に向けた調査研究、プログラム、作品を紹介。',
      en: 'Website for an arts centre in Akita presenting its studies, programmes, and works for the local community.',
    },
    tools: 'WordPress, PHP',
    image: shot('artscenter-akita-jp'),
    liveUrl: 'https://www.artscenter-akita.jp/',
    visitShort: 'artscenter-akita.jp',
  },
  {
    name: 'Haru-ni App Factory',
    cat: 'corporate',
    label: { ja: 'ゲームスタジオサイト', en: 'Game Studio Site' },
    desc: {
      ja: '国内外のパートナーとゲームを開発する鹿児島のゲーム開発スタジオのコーポレートサイト。',
      en: 'Corporate site for a Kagoshima game development studio that builds games with partners in Japan and overseas.',
    },
    tools: 'Nuxt, Vue.js',
    image: shot('haru-ni-net'),
    liveUrl: 'https://haru-ni.net/',
    visitShort: 'haru-ni.net',
  },
  {
    name: { ja: 'インコム・ジャパン', en: 'Incomm Japan' },
    cat: 'corporate',
    label: { ja: 'コーポレートサイト', en: 'Corporate Site' },
    desc: {
      ja: '事業領域、サービス、ニュース、お問い合わせ情報を掲載したコーポレートサイト。',
      en: 'Corporate website presenting the company’s business areas, services, news, and contact information.',
    },
    tools: 'WordPress, PHP, jQuery',
    image: shot('incomm-jp'),
    liveUrl: 'https://incomm.jp/',
    visitShort: 'incomm.jp',
  },
  {
    name: { ja: 'エアリク（AirRecruit）', en: 'AirRecruit (エアリク)' },
    cat: 'corporate',
    label: { ja: 'BtoBサービスサイト', en: 'B2B Service Site' },
    desc: {
      ja: '自社のカルチャーに合う人材を集める、採用特化型SNS運用代行サービスのサイト。',
      en: 'Service site for a recruiting-focused social media management agency that helps companies attract candidates who fit their culture.',
    },
    tools: 'HTML/CSS, jQuery, Responsive',
    image: shot('sns-agency-rc-group-co-jp'),
    liveUrl: 'https://sns-agency.rc-group.co.jp/',
    visitShort: 'sns-agency.rc-group.co.jp',
  },
  {
    name: 'SAKIYOMI',
    cat: 'corporate',
    label: { ja: 'BtoBサービスページ', en: 'B2B Service Page' },
    desc: {
      ja: 'スタートアップから大企業までのInstagram運用支援を紹介する、Instagramマーケティング会社のサービスページ。',
      en: 'Service page for an Instagram marketing agency, laying out its growth support offering for businesses from startups to large companies.',
    },
    tools: 'WordPress, Elementor, PHP',
    image: shot('sns-sakiyomi-com-blog-agent3'),
    liveUrl: 'https://sns-sakiyomi.com/blog/agent3/',
    visitShort: 'sns-sakiyomi.com',
  },
  {
    name: 'webcoco',
    cat: 'corporate',
    label: { ja: 'マーケティングサイト', en: 'Marketing Site' },
    desc: {
      ja: '工務店・建設会社向けのウェブ制作サービスのマーケティングサイト。問い合わせ獲得を重視した設計。',
      en: 'Marketing site for a web production service built for home builders and construction companies, focused on generating enquiries.',
    },
    tools: 'WordPress, PHP, SEO',
    image: shot('webcoco-jp'),
    liveUrl: 'https://www.webcoco.jp/',
    visitShort: 'webcoco.jp',
  },
  {
    name: { ja: 'クラシスホーム', en: 'Clasis Home' },
    cat: 'corporate',
    label: { ja: '住宅メーカー', en: 'Home Builder' },
    desc: {
      ja: '東海エリアの注文住宅メーカーのウェブサイト。施工事例、モデルハウス、相談予約への導線を設計。',
      en: 'Website for a custom home builder in the Tokai region, showcasing designs, model homes, and lead capture for consultations.',
    },
    tools: 'WordPress, PHP, jQuery',
    image: shot('clasishome-jp'),
    liveUrl: 'https://www.clasishome.jp/',
    visitShort: 'clasishome.jp',
  },
  {
    name: { ja: 'ジラフ計画', en: 'Giraffe Keikaku' },
    cat: 'corporate',
    label: { ja: 'コーポレートサイト', en: 'Corporate Site' },
    desc: {
      ja: '展示会ブースの設計・施工・装飾・備品レンタル・現場管理を手がける企業のサイト。',
      en: 'Site for an exhibition booth company handling design, construction, decoration, equipment rental, and on-site management.',
    },
    tools: 'WordPress, PHP, jQuery',
    image: shot('giraffe-planning-jp'),
    liveUrl: 'https://giraffe-planning.jp/',
    visitShort: 'giraffe-planning.jp',
  },
  {
    name: { ja: 'いこまともみ産科クリニック', en: 'Ikoma Tomomi Ladies Clinic' },
    cat: 'corporate',
    label: { ja: 'クリニックサイト', en: 'Clinic Site' },
    desc: {
      ja: '石川県白山市の産科クリニックのウェブサイト。妊婦健診、出産、産後ケアを紹介。',
      en: 'Website for an obstetrics clinic in Hakusan, Ishikawa, covering prenatal care, childbirth, and postnatal support.',
    },
    tools: 'WordPress, PHP, AIOSEO',
    image: shot('ikomatomomi-sanka-clinic-com'),
    liveUrl: 'https://ikomatomomi-sanka-clinic.com/',
    visitShort: 'Clinic site',
  },
  {
    name: { ja: 'トアロード整骨院', en: 'Toa Road Osteopathic Clinic' },
    cat: 'corporate',
    label: { ja: '整骨院サイト', en: 'Clinic Site' },
    desc: {
      ja: '神戸・元町駅と三宮駅の近くにある整骨院のウェブサイト。',
      en: 'Website for an osteopathic clinic near Motomachi and Sannomiya stations in Kobe.',
    },
    tools: 'WordPress, PHP, Local SEO',
    image: shot('toa-seikotsu-com'),
    liveUrl: 'https://www.toa-seikotsu.com/',
    visitShort: 'toa-seikotsu.com',
  },
  {
    name: 'Hair & Beauty Rayfield',
    cat: 'corporate',
    label: { ja: 'サロンサイト', en: 'Salon Site' },
    desc: {
      ja: '店舗、スタイリスト、採用情報、スタイル集を紹介するヘアサロングループのウェブサイト。',
      en: 'Website for a hair salon group presenting its salons, stylists, recruiting, and portfolio of work.',
    },
    tools: 'WordPress, PHP, jQuery',
    image: shot('rayfield-jp'),
    liveUrl: 'https://rayfield.jp/',
    visitShort: 'rayfield.jp',
  },
  {
    name: 'MAQUIA',
    cat: 'corporate',
    label: { ja: 'サロンチェーンサイト', en: 'Salon Chain Site' },
    desc: {
      ja: '全国展開するまつげエクステサロンのウェブサイト。店舗一覧、メニュー、採用情報を掲載。',
      en: 'Website for a nationwide eyelash extension chain with store listings, menus, and recruiting.',
    },
    tools: 'HTML/CSS, jQuery, Responsive',
    image: shot('e-maquia-jp'),
    liveUrl: 'https://e-maquia.jp/',
    visitShort: 'e-maquia.jp',
  },

  /* --------------------------------------------------------- E-commerce */
  {
    name: { ja: '不二家 ファミリータウン', en: 'Fujiya Family Town' },
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: {
      ja: 'ペコちゃん人形から文具・日用品まで、不二家キャラクターグッズの公式オンラインショップ。',
      en: 'Official online shop for Fujiya character goods, from Peko-chan dolls to stationery and everyday items.',
    },
    tools: 'MakeShop, Vue.js, jQuery',
    image: shot('family-town-jp'),
    liveUrl: 'https://family-town.jp/',
    visitShort: 'family-town.jp',
  },
  {
    name: { ja: 'わかさいも本舗', en: 'Wakasaimo Honpo' },
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: {
      ja: '北海道の老舗菓子店の公式オンラインストア。ギフトセット、送料無料ライン、電話注文に対応。',
      en: 'Official online store for a long-established Hokkaido confectioner, with gift sets, shipping thresholds, and phone ordering.',
    },
    tools: 'MakeShop, jQuery, Payments',
    image: shot('shop-wakasaimo-com'),
    liveUrl: 'https://shop.wakasaimo.com/',
    visitShort: 'shop.wakasaimo.com',
  },
  {
    name: { ja: 'ファリーナコーポレーション', en: 'Farina Corporation' },
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: {
      ja: 'うどん・パン用小麦粉、麺類、製麺用品を販売する香川の製粉会社の直販ショップ。',
      en: 'Direct-sales shop for a Kagawa flour mill selling udon and bread flours, noodles, and noodle-making tools.',
    },
    tools: 'MakeShop, jQuery',
    image: shot('farina-co-jp'),
    liveUrl: 'https://farina.co.jp/',
    visitShort: 'farina.co.jp',
  },
  {
    name: { ja: '田中農場', en: 'Tanaka Farm' },
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: {
      ja: '精米したての米、ねぎ、大豆を販売する鳥取県八頭町の農場のオンラインショップ。',
      en: 'Online shop for a farm in Yazu, Tottori selling freshly milled rice, green onions, and soybeans.',
    },
    tools: 'MakeShop, WordPress, jQuery',
    image: shot('farm-tanaka-jp'),
    liveUrl: 'https://www.farm-tanaka.jp/',
    visitShort: 'farm-tanaka.jp',
  },
  {
    name: { ja: 'ELECTRON 公式オンラインショップ', en: 'ELECTRON Online Shop' },
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: {
      ja: '新製品の発売やキャンペーンを展開するスキンケアブランドの公式オンラインストア。',
      en: 'Official online store for a skincare brand, featuring new product launches and campaigns.',
    },
    tools: 'MakeShop, jQuery',
    image: shot('shop-el-gm-beauty-jp'),
    liveUrl: 'https://shop.el.gm-beauty.jp/',
    visitShort: 'shop.el.gm-beauty.jp',
  },
  {
    name: { ja: 'ギズ屋台', en: 'Giz Yatai' },
    cat: 'ecommerce',
    label: 'Shopify',
    desc: {
      ja: 'ギズモード・ジャパンのテーマ型Shopifyストア。ドット絵の屋台デザインで希少・オリジナルガジェットを販売。',
      en: 'Themed Shopify store for Gizmodo Japan, selling rare and original gadgets through a pixel-art street-stall design.',
    },
    tools: 'Shopify, Liquid, jQuery',
    image: shot('yatai-gizmodo-jp'),
    liveUrl: 'https://yatai.gizmodo.jp/',
    visitShort: 'yatai.gizmodo.jp',
  },
  {
    name: 'IBUKI bottled tea',
    cat: 'ecommerce',
    label: 'ecforce',
    desc: {
      ja: 'プレミアムなボトリング日本茶・紅茶ブランドの公式オンラインショップ。',
      en: 'Official online shop for a premium bottled Japanese and black tea brand.',
    },
    tools: 'ecforce, WordPress, jQuery',
    image: shot('ibuki-tea-com'),
    liveUrl: 'https://ibuki-tea.com/',
    visitShort: 'ibuki-tea.com',
  },
  {
    name: { ja: 'サッポロクラシック', en: 'Sapporo Classic' },
    cat: 'ecommerce',
    label: 'ecforce',
    desc: {
      ja: 'D2Cコマースプラットフォームecforceで構築したオンラインストア。',
      en: 'Online store built on the ecforce D2C commerce platform.',
    },
    tools: 'ecforce',
    image: '',
    liveUrl: 'https://sapporo-classic.com/',
    visitShort: 'sapporo-classic.com',
  },
  {
    name: 'DRIMO STORE',
    cat: 'ecommerce',
    label: 'BASE',
    desc: {
      ja: 'キャンピングカー・車中泊メディアブランドの公式グッズストア。',
      en: 'Official merchandise store for a camper van and car-camping media brand.',
    },
    tools: 'BASE, jQuery',
    image: shot('store-drimo-jp'),
    liveUrl: 'https://store.drimo.jp/',
    visitShort: 'store.drimo.jp',
  },
  {
    name: 'Kuma Medaka Farm',
    cat: 'ecommerce',
    label: 'BASE',
    desc: {
      ja: '高品質な改良メダカを販売する熊本のブリーダーのオンラインショップ。',
      en: 'Online shop for a Kumamoto breeder selling high-quality selectively bred medaka fish.',
    },
    tools: 'BASE, jQuery',
    image: shot('medaka-loki-life-com'),
    liveUrl: 'https://medaka.loki-life.com/',
    visitShort: 'medaka.loki-life.com',
  },
  {
    name: 'Vitawake',
    cat: 'ecommerce',
    label: 'Wix + Ecwid',
    desc: {
      ja: 'パーソナライズされたヴィーガンビタミン・サプリメントを販売するイギリスのECサイト。',
      en: 'UK e-commerce site for personalised vegan vitamins and supplements.',
    },
    tools: 'Wix, Ecwid, Payments',
    image: shot('vitawake-co-uk'),
    liveUrl: 'https://www.vitawake.co.uk/',
    visitShort: 'vitawake.co.uk',
  },

  /* ------------------------------------------------------ Landing pages */
  {
    name: { ja: 'Penmark（ペンマーク）', en: 'Penmark' },
    cat: 'lp',
    label: { ja: 'アプリLP', en: 'App Landing Page' },
    desc: {
      ja: '大学生向けの時間割・履修管理アプリのランディングページ。',
      en: 'Landing page for a timetable and course-management app for university students.',
    },
    tools: 'Nuxt, Vue.js, App Store Links',
    image: shot('penmark-jp'),
    liveUrl: 'https://penmark.jp/',
    visitShort: 'penmark.jp',
  },
  {
    name: { ja: '菊正宗 嘉宝', en: 'Kikumasamune KAHO' },
    cat: 'lp',
    label: { ja: '商品ページ', en: 'Product Page' },
    desc: {
      ja: 'フラッグシップの純米大吟醸のブランドページ。豊かなビジュアルとストーリーテリングを軸に構成。',
      en: 'Brand page for a flagship junmai daiginjo sake, built around rich visuals and storytelling.',
    },
    tools: 'Craft CMS, JavaScript, Animation',
    image: '',
    liveUrl: 'https://www.kikumasamune.co.jp/products/kaho/',
    visitShort: 'KAHO page',
  },
  {
    name: { ja: '八百彦本店 一升餅', en: 'Yaohiko Isshou Mochi' },
    cat: 'lp',
    label: { ja: 'キャンペーンLP', en: 'Campaign LP' },
    desc: {
      ja: '名古屋の老舗仕出し店が提供する一升餅（初誕生祝い）のキャンペーンLP。',
      en: 'Campaign landing page for a traditional first-birthday rice-cake celebration offered by a long-established Nagoya caterer.',
    },
    tools: 'HTML/CSS, JavaScript, Animation',
    image: '',
    liveUrl: 'https://www.yaohiko.co.jp/isshoumochi/',
    visitShort: 'Isshou Mochi LP',
  },
  {
    name: 'Ebisu Kubono Eye Clinic',
    cat: 'lp',
    label: { ja: 'クリニックLP', en: 'Clinic LP' },
    desc: {
      ja: '渋谷に新規開院した眼科のウェブサイト兼ランディングページ。一般診療と白内障手術を紹介。',
      en: 'Website and landing page for a newly opened eye clinic in Shibuya offering general care and cataract surgery.',
    },
    tools: 'WordPress, PHP, AIOSEO',
    image: shot('ebisu-ganka-com'),
    liveUrl: 'https://www.ebisu-ganka.com/',
    visitShort: 'ebisu-ganka.com',
  },
  {
    name: { ja: 'ごちくるNow', en: 'Gochikuru Now' },
    cat: 'lp',
    label: 'LP + kintone',
    desc: {
      ja: 'オフィス向けランチデリバリーサービスのランディングページ。問い合わせにkintoneを連携。',
      en: 'Landing page for an office lunch delivery service, with kintone on the page for enquiries.',
    },
    tools: 'Astro, kintone, Lead Forms',
    image: shot('gochikurunow-com'),
    liveUrl: 'https://gochikurunow.com/',
    visitShort: 'gochikurunow.com',
  },
  {
    name: 'Kurono Reuse',
    cat: 'lp',
    label: 'STUDIO LP',
    desc: {
      ja: '不用品買取サービスのランディングページ。大きな文字と分かりやすい導線でシニア層向けに設計。',
      en: 'Landing page for a used-goods buyback service, designed for an older audience with large type and clear calls to action.',
    },
    tools: 'STUDIO, Nuxt, Vue.js',
    image: shot('cr966-com'),
    liveUrl: 'https://cr966.com/',
    visitShort: 'cr966.com',
  },

  /* ------------------------------------------------ Web apps & systems */
  {
    name: 'STORES',
    cat: 'systems',
    label: { ja: 'コマースプラットフォーム', en: 'Commerce Platform' },
    desc: {
      ja: 'POS、決済、予約、ネットショップ、モバイルオーダーを1つのアカウントで扱う店舗運営プラットフォーム。',
      en: 'Store operations platform combining POS, payments, reservations, online shops, and mobile ordering in one account.',
    },
    tools: 'Next.js, React, Payments, Reservations',
    image: shot('stores-jp'),
    liveUrl: 'https://stores.jp/',
    visitShort: 'stores.jp',
  },
  {
    name: { ja: 'いえらぶCLOUD', en: 'ielove Cloud' },
    cat: 'systems',
    label: 'CRM SaaS',
    desc: {
      ja: '不動産会社向けのクラウド業務プラットフォーム。顧客管理と物件業務をカバー。',
      en: 'Cloud business platform for real estate companies, covering customer management and property operations.',
    },
    tools: 'CRM, SaaS, Customer Management',
    image: '',
    liveUrl: 'https://ielove-cloud.jp/',
    visitShort: 'ielove-cloud.jp',
  },
  {
    name: { ja: 'ソースネクスト 盗難対策サービス', en: 'SourceNext Theft Protection' },
    cat: 'systems',
    label: { ja: 'Pythonシステム', en: 'Python System' },
    desc: {
      ja: 'デバイス盗難対策サービスのアカウントポータル。ログイン制のため、公開されているのは入口画面のみ。',
      en: 'Account portal for a device theft-protection service. Behind a login, so only the entry screen is public.',
    },
    tools: 'Python, Authentication, Web Portal',
    image: shot('vsm-sourcenext-com'),
    shareUrl: false,
    visitShort: 'SourceNext portal',
  },
  {
    name: 'moovie',
    cat: 'systems',
    label: { ja: 'Pythonシステム', en: 'Python System' },
    desc: {
      ja: '会員制の業務向けWebアプリケーション。ログイン制のため、公開されているのは入口画面のみ。',
      en: 'Members-only business web application. Behind a login, so only the entry screen is public.',
    },
    tools: 'Python, Authentication, Web App',
    image: shot('moovie-farmers-s-co-jp'),
    shareUrl: false,
    visitShort: 'moovie',
  },
  {
    name: 'Qiita',
    cat: 'systems',
    label: { ja: 'Webプラットフォーム', en: 'Web Platform' },
    desc: {
      ja: 'エンジニアがプログラミングのTipsやノウハウを記録・公開する知識共有プラットフォーム。',
      en: 'Knowledge-sharing platform where engineers record and publish programming tips and know-how.',
    },
    tools: 'Web Platform, Search, User Accounts',
    image: shot('qiita-com'),
    liveUrl: 'https://qiita.com/',
    visitShort: 'qiita.com',
  },

  /* -------------------------------------------------------- CMS & no-code */
  {
    name: { ja: 'Ishikawa Travel（石川県観光ガイド 英語版）', en: 'Ishikawa Travel' },
    cat: 'cms',
    label: 'Craft CMS',
    desc: {
      ja: '石川県公式の英語版観光ガイド。文化、歴史、食、自然を紹介。',
      en: 'Official English-language travel guide to Ishikawa Prefecture, covering culture, history, food, and nature.',
    },
    tools: 'Craft CMS, Multilingual, JavaScript',
    image: shot('ishikawatravel-jp-en'),
    liveUrl: 'https://www.ishikawatravel.jp/en/',
    visitShort: 'ishikawatravel.jp',
  },
  {
    name: { ja: '浅草九倶楽部', en: 'Asakusa Kokono Club' },
    cat: 'cms',
    label: 'Craft CMS',
    desc: {
      ja: '浅草の劇場・ホテル複合施設のサイト。公演スケジュールとエンタメニュースを掲載。',
      en: 'Site for an Asakusa theatre and hotel complex, with performance schedules and entertainment news.',
    },
    tools: 'Craft CMS, JavaScript',
    image: shot('asakusa-kokono-com'),
    liveUrl: 'https://asakusa-kokono.com/',
    visitShort: 'asakusa-kokono.com',
  },
  {
    name: { ja: 'アンヌプリロッジ ニセコ', en: 'The Annupuri Lodge Niseko' },
    cat: 'cms',
    label: 'Craft CMS',
    desc: {
      ja: 'ニセコ・アンヌプリゴンドラのそばにあるスキーロッジの宿泊サイト。客室、ダイニング、予約に対応。',
      en: 'Accommodation site for a ski lodge beside the Annupuri gondola in Niseko, with rooms, dining, and booking.',
    },
    tools: 'Craft CMS, jQuery, Booking',
    image: shot('annupurilodge-com'),
    liveUrl: 'https://annupurilodge.com/',
    visitShort: 'annupurilodge.com',
  },
  {
    name: 'Dmed',
    cat: 'cms',
    label: 'Craft CMS',
    desc: {
      ja: '科学論文の共同執筆・編集プラットフォームのプロダクトサイト。',
      en: 'Product site for a collaborative authoring and editing platform for scientific writing.',
    },
    tools: 'Craft CMS, JavaScript',
    image: shot('dmccorp-co-jp'),
    liveUrl: 'https://dmccorp.co.jp/',
    visitShort: 'dmccorp.co.jp',
  },
  {
    name: { ja: '板垣・四反田研究室', en: 'Itagaki–Shitanda Laboratory' },
    cat: 'cms',
    label: 'Wix',
    desc: {
      ja: '東京理科大学の電気分析化学研究室のバイリンガルサイト。',
      en: 'Bilingual website for an electroanalytical chemistry lab at Tokyo University of Science.',
    },
    tools: 'Wix, Multilingual',
    image: shot('islab-ca-noda-tus-ac-jp'),
    liveUrl: 'https://www.islab.ca.noda.tus.ac.jp/?lang=en',
    visitShort: 'Lab site',
  },
  {
    name: { ja: 'POYL 整骨院', en: 'POYL Osteopathic Clinic' },
    cat: 'cms',
    label: 'Wix',
    desc: {
      ja: '世田谷の整骨院・鍼灸院のウェブサイト。オンライン予約に対応。',
      en: 'Website for an osteopathic and acupuncture clinic in Setagaya, with online booking.',
    },
    tools: 'Wix, Online Booking',
    image: shot('poyl-net'),
    liveUrl: 'https://www.poyl.net/',
    visitShort: 'poyl.net',
  },
  {
    name: 'ALIVE Hair Salon',
    cat: 'cms',
    label: 'Wegeey',
    desc: {
      ja: 'バレイヤージュやハイライトカラーで知られる原宿・吉祥寺のヘアサロンのウェブサイト。',
      en: 'Website for a hair salon in Harajuku and Kichijoji known for balayage and highlight colouring.',
    },
    tools: 'Wegeey, jQuery',
    image: shot('alive-hair-com'),
    liveUrl: 'http://www.alive-hair.com/',
    visitShort: 'alive-hair.com',
  },
  {
    name: 'Lacab.hair',
    cat: 'cms',
    label: 'Wegeey',
    desc: {
      ja: 'キッズスペースとヘッドスパメニューを備えた名古屋・守山のプライベートヘアサロンのウェブサイト。',
      en: 'Website for a private hair salon in Moriyama, Nagoya, with a kids’ space and head spa menu.',
    },
    tools: 'Wegeey, jQuery',
    image: shot('lacabhair-com'),
    liveUrl: 'https://lacabhair.com/',
    visitShort: 'lacabhair.com',
  },

  /* ---------------------------------------------------------- Web3 */
  {
    name: 'Famous Fox Federation',
    cat: 'web3',
    label: 'Solana NFT',
    desc: {
      ja: 'アルゴリズム生成された7,777体のキツネによるSolana NFTコレクション。コミュニティツール、ラッフル、ミッション機能を備える。',
      en: 'Solana NFT collection of 7,777 algorithmically generated foxes, with community tools, raffles, and missions.',
    },
    tools: 'Solana, NFT, Web3',
    image: shot('famousfoxes-com'),
    liveUrl: 'https://famousfoxes.com/',
    visitShort: 'famousfoxes.com',
  },
  {
    name: 'Treedefi',
    cat: 'web3',
    label: { ja: 'DeFiプラットフォーム', en: 'DeFi Platform' },
    desc: {
      ja: 'ESG領域のクリプトを対象としたDeFiプラットフォーム。取引所、ツール、NFTのセクションを持つ。',
      en: 'DeFi platform aimed at the ESG crypto space, with exchange, tools, and NFT sections.',
    },
    tools: 'Solidity, DeFi, ERC20, Web3.js',
    image: shot('treedefi-com'),
    liveUrl: 'https://treedefi.com/',
    visitShort: 'treedefi.com',
  },

  /* ------------------------------------------------------ Apps & games */
  {
    name: { ja: '乃木恋', en: 'NOGIKOI' },
    cat: 'apps',
    label: { ja: 'ゲームアプリサイト', en: 'Game App Site' },
    desc: {
      ja: '乃木坂46の恋愛ゲームアプリの公式サイト。メンバー写真、スペシャル動画、アプリストアへのリンクを掲載。',
      en: 'Official site for the Nogizaka46 romance game app, with member photos, special videos, and app store downloads.',
    },
    tools: 'PHP, jQuery, App Store Links',
    image: shot('nogikoi-jp'),
    liveUrl: 'https://nogikoi.jp/',
    visitShort: 'nogikoi.jp',
  },
  {
    name: 'unityroom',
    cat: 'apps',
    label: { ja: 'ゲームプラットフォーム', en: 'Game Platform' },
    desc: {
      ja: 'Unity製の数万本のゲームを公開する無料ブラウザゲームプラットフォーム。デイリーランキングを備える。',
      en: 'Free browser game platform hosting tens of thousands of games made with Unity, with daily rankings.',
    },
    tools: 'Unity, WebGL, Game Hosting',
    image: shot('unityroom-com'),
    liveUrl: 'https://unityroom.com/',
    visitShort: 'unityroom.com',
  },
];
