/**
 * Project list. Every entry was loaded in a real browser to confirm it is live.
 *
 *   cat      filter key — see `projectCategories` in config.js
 *   label    small caption above the title (platform or project type)
 *   tools    comma-separated; shown as pills. Where the live site exposes its
 *            platform (WordPress, Shopify, MakeShop…) that is what is listed.
 *   image    screenshot of the live site; empty → generated placeholder
 *   shareUrl false → "Private" badge and no visit button (login-only systems)
 */

const shot = (name) => `./images/work/${name}.jpg`;

export const projects = [
  /* ---------------------------------------------------------- Corporate */
  {
    name: 'Sekisui Chemical',
    cat: 'corporate',
    label: 'Corporate Site',
    desc: 'Corporate website for a major Japanese manufacturer, covering company information, sustainability, investor relations, products, and careers.',
    tools: 'HTML/CSS, JavaScript, Responsive, IR Pages',
    image: shot('sekisui-co-jp'),
    liveUrl: 'https://www.sekisui.co.jp/',
    visitShort: 'sekisui.co.jp',
  },
  {
    name: 'Nagashima Ohno & Tsunematsu',
    cat: 'corporate',
    label: 'Law Firm Site',
    desc: 'Website for one of Japan’s leading full-service law firms, presenting practice areas, lawyer profiles, and publications.',
    tools: 'WordPress, PHP, Vue.js',
    image: shot('noandt-com'),
    liveUrl: 'https://www.noandt.com/',
    visitShort: 'noandt.com',
  },
  {
    name: 'AZX Professionals Group',
    cat: 'corporate',
    label: 'Professional Firm Site',
    desc: 'Site for a professional firm providing startups with one-stop legal, patent, tax, accounting, and labour services.',
    tools: 'WordPress, PHP, jQuery',
    image: shot('azx-co-jp'),
    liveUrl: 'https://www.azx.co.jp/',
    visitShort: 'azx.co.jp',
  },
  {
    name: 'Otsuka Shokai',
    cat: 'corporate',
    label: 'IT Solutions',
    desc: 'Website for an IT and office-systems company covering system sales, implementation support, training, and maintenance services.',
    tools: 'HTML/CSS, jQuery, Responsive',
    image: shot('otsuka-shokai-co-jp'),
    liveUrl: 'https://www.otsuka-shokai.co.jp/',
    visitShort: 'otsuka-shokai.co.jp',
  },
  {
    name: 'Systems Nakashima',
    cat: 'corporate',
    label: 'System Developer',
    desc: 'Corporate site for a system development company in Okayama, Tokyo, and Osaka offering custom systems, AI development, and packaged CAD and SFA software.',
    tools: 'kintone, jQuery, HTML/CSS',
    image: shot('systems-nakashima-co-jp'),
    liveUrl: 'https://www.systems.nakashima.co.jp/',
    visitShort: 'systems.nakashima.co.jp',
  },
  {
    name: 'MIMIGURI',
    cat: 'corporate',
    label: 'Consulting Firm',
    desc: 'Website for a management consulting firm specialising in people and organisations.',
    tools: 'Next.js, React, TypeScript',
    image: shot('mimiguri-co-jp'),
    liveUrl: 'https://mimiguri.co.jp/',
    visitShort: 'mimiguri.co.jp',
  },
  {
    name: 'Digital Garage Careers',
    cat: 'corporate',
    label: 'Recruiting Site',
    desc: 'Recruiting site with mid-career, new-graduate, and internship listings, plus employee interviews, benefits, and career path information.',
    tools: 'WordPress, PHP, Responsive',
    image: shot('recruit-garage-co-jp'),
    liveUrl: 'https://recruit.garage.co.jp/',
    visitShort: 'recruit.garage.co.jp',
  },
  {
    name: 'Leapy',
    cat: 'corporate',
    label: 'Corporate Site',
    desc: 'Corporate site for a Gifu-based company offering website production, site operation, and recruitment outsourcing.',
    tools: 'WordPress, PHP, jQuery',
    image: shot('leapy-jp'),
    liveUrl: 'https://leapy.jp/',
    visitShort: 'leapy.jp',
  },
  {
    name: 'Arts Center Akita',
    cat: 'corporate',
    label: 'Arts Organisation',
    desc: 'Website for an arts centre in Akita presenting its studies, programmes, and works for the local community.',
    tools: 'WordPress, PHP',
    image: shot('artscenter-akita-jp'),
    liveUrl: 'https://www.artscenter-akita.jp/',
    visitShort: 'artscenter-akita.jp',
  },
  {
    name: 'Haru-ni App Factory',
    cat: 'corporate',
    label: 'Game Studio Site',
    desc: 'Corporate site for a Kagoshima game development studio that builds games with partners in Japan and overseas.',
    tools: 'Nuxt, Vue.js',
    image: shot('haru-ni-net'),
    liveUrl: 'https://haru-ni.net/',
    visitShort: 'haru-ni.net',
  },
  {
    name: 'Incomm Japan',
    cat: 'corporate',
    label: 'Corporate Site',
    desc: 'Corporate website presenting the company’s business areas, services, news, and contact information.',
    tools: 'WordPress, PHP, jQuery',
    image: shot('incomm-jp'),
    liveUrl: 'https://incomm.jp/',
    visitShort: 'incomm.jp',
  },
  {
    name: 'AirRecruit (エアリク)',
    cat: 'corporate',
    label: 'B2B Service Site',
    desc: 'Service site for a recruiting-focused social media management agency that helps companies attract candidates who fit their culture.',
    tools: 'HTML/CSS, jQuery, Responsive',
    image: shot('sns-agency-rc-group-co-jp'),
    liveUrl: 'https://sns-agency.rc-group.co.jp/',
    visitShort: 'sns-agency.rc-group.co.jp',
  },
  {
    name: 'SAKIYOMI',
    cat: 'corporate',
    label: 'B2B Service Page',
    desc: 'Service page for an Instagram marketing agency, laying out its growth support offering for businesses from startups to large companies.',
    tools: 'WordPress, Elementor, PHP',
    image: shot('sns-sakiyomi-com-blog-agent3'),
    liveUrl: 'https://sns-sakiyomi.com/blog/agent3/',
    visitShort: 'sns-sakiyomi.com',
  },
  {
    name: 'webcoco',
    cat: 'corporate',
    label: 'Marketing Site',
    desc: 'Marketing site for a web production service built for home builders and construction companies, focused on generating enquiries.',
    tools: 'WordPress, PHP, SEO',
    image: shot('webcoco-jp'),
    liveUrl: 'https://www.webcoco.jp/',
    visitShort: 'webcoco.jp',
  },
  {
    name: 'Clasis Home',
    cat: 'corporate',
    label: 'Home Builder',
    desc: 'Website for a custom home builder in the Tokai region, showcasing designs, model homes, and lead capture for consultations.',
    tools: 'WordPress, PHP, jQuery',
    image: shot('clasishome-jp'),
    liveUrl: 'https://www.clasishome.jp/',
    visitShort: 'clasishome.jp',
  },
  {
    name: 'Giraffe Keikaku',
    cat: 'corporate',
    label: 'Corporate Site',
    desc: 'Site for an exhibition booth company handling design, construction, decoration, equipment rental, and on-site management.',
    tools: 'WordPress, PHP, jQuery',
    image: shot('giraffe-planning-jp'),
    liveUrl: 'https://giraffe-planning.jp/',
    visitShort: 'giraffe-planning.jp',
  },
  {
    name: 'Ikoma Tomomi Ladies Clinic',
    cat: 'corporate',
    label: 'Clinic Site',
    desc: 'Website for an obstetrics clinic in Hakusan, Ishikawa, covering prenatal care, childbirth, and postnatal support.',
    tools: 'WordPress, PHP, AIOSEO',
    image: shot('ikomatomomi-sanka-clinic-com'),
    liveUrl: 'https://ikomatomomi-sanka-clinic.com/',
    visitShort: 'Clinic site',
  },
  {
    name: 'Toa Road Osteopathic Clinic',
    cat: 'corporate',
    label: 'Clinic Site',
    desc: 'Website for an osteopathic clinic near Motomachi and Sannomiya stations in Kobe.',
    tools: 'WordPress, PHP, Local SEO',
    image: shot('toa-seikotsu-com'),
    liveUrl: 'https://www.toa-seikotsu.com/',
    visitShort: 'toa-seikotsu.com',
  },
  {
    name: 'Hair & Beauty Rayfield',
    cat: 'corporate',
    label: 'Salon Site',
    desc: 'Website for a hair salon group presenting its salons, stylists, recruiting, and portfolio of work.',
    tools: 'WordPress, PHP, jQuery',
    image: shot('rayfield-jp'),
    liveUrl: 'https://rayfield.jp/',
    visitShort: 'rayfield.jp',
  },
  {
    name: 'MAQUIA',
    cat: 'corporate',
    label: 'Salon Chain Site',
    desc: 'Website for a nationwide eyelash extension chain with store listings, menus, and recruiting.',
    tools: 'HTML/CSS, jQuery, Responsive',
    image: shot('e-maquia-jp'),
    liveUrl: 'https://e-maquia.jp/',
    visitShort: 'e-maquia.jp',
  },

  /* --------------------------------------------------------- E-commerce */
  {
    name: 'Fujiya Family Town',
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: 'Official online shop for Fujiya character goods, from Peko-chan dolls to stationery and everyday items.',
    tools: 'MakeShop, Vue.js, jQuery',
    image: shot('family-town-jp'),
    liveUrl: 'https://family-town.jp/',
    visitShort: 'family-town.jp',
  },
  {
    name: 'Wakasaimo Honpo',
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: 'Official online store for a long-established Hokkaido confectioner, with gift sets, shipping thresholds, and phone ordering.',
    tools: 'MakeShop, jQuery, Payments',
    image: shot('shop-wakasaimo-com'),
    liveUrl: 'https://shop.wakasaimo.com/',
    visitShort: 'shop.wakasaimo.com',
  },
  {
    name: 'Farina Corporation',
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: 'Direct-sales shop for a Kagawa flour mill selling udon and bread flours, noodles, and noodle-making tools.',
    tools: 'MakeShop, jQuery',
    image: shot('farina-co-jp'),
    liveUrl: 'https://farina.co.jp/',
    visitShort: 'farina.co.jp',
  },
  {
    name: 'Tanaka Farm',
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: 'Online shop for a farm in Yazu, Tottori selling freshly milled rice, green onions, and soybeans.',
    tools: 'MakeShop, WordPress, jQuery',
    image: shot('farm-tanaka-jp'),
    liveUrl: 'https://www.farm-tanaka.jp/',
    visitShort: 'farm-tanaka.jp',
  },
  {
    name: 'ELECTRON Online Shop',
    cat: 'ecommerce',
    label: 'MakeShop',
    desc: 'Official online store for a skincare brand, featuring new product launches and campaigns.',
    tools: 'MakeShop, jQuery',
    image: shot('shop-el-gm-beauty-jp'),
    liveUrl: 'https://shop.el.gm-beauty.jp/',
    visitShort: 'shop.el.gm-beauty.jp',
  },
  {
    name: 'Giz Yatai',
    cat: 'ecommerce',
    label: 'Shopify',
    desc: 'Themed Shopify store for Gizmodo Japan, selling rare and original gadgets through a pixel-art street-stall design.',
    tools: 'Shopify, Liquid, jQuery',
    image: shot('yatai-gizmodo-jp'),
    liveUrl: 'https://yatai.gizmodo.jp/',
    visitShort: 'yatai.gizmodo.jp',
  },
  {
    name: 'IBUKI bottled tea',
    cat: 'ecommerce',
    label: 'ecforce',
    desc: 'Official online shop for a premium bottled Japanese and black tea brand.',
    tools: 'ecforce, WordPress, jQuery',
    image: shot('ibuki-tea-com'),
    liveUrl: 'https://ibuki-tea.com/',
    visitShort: 'ibuki-tea.com',
  },
  {
    name: 'Sapporo Classic',
    cat: 'ecommerce',
    label: 'ecforce',
    desc: 'Online store built on the ecforce D2C commerce platform.',
    tools: 'ecforce',
    image: '',
    liveUrl: 'https://sapporo-classic.com/',
    visitShort: 'sapporo-classic.com',
  },
  {
    name: 'DRIMO STORE',
    cat: 'ecommerce',
    label: 'BASE',
    desc: 'Official merchandise store for a camper van and car-camping media brand.',
    tools: 'BASE, jQuery',
    image: shot('store-drimo-jp'),
    liveUrl: 'https://store.drimo.jp/',
    visitShort: 'store.drimo.jp',
  },
  {
    name: 'Kuma Medaka Farm',
    cat: 'ecommerce',
    label: 'BASE',
    desc: 'Online shop for a Kumamoto breeder selling high-quality selectively bred medaka fish.',
    tools: 'BASE, jQuery',
    image: shot('medaka-loki-life-com'),
    liveUrl: 'https://medaka.loki-life.com/',
    visitShort: 'medaka.loki-life.com',
  },
  {
    name: 'Vitawake',
    cat: 'ecommerce',
    label: 'Wix + Ecwid',
    desc: 'UK e-commerce site for personalised vegan vitamins and supplements.',
    tools: 'Wix, Ecwid, Payments',
    image: shot('vitawake-co-uk'),
    liveUrl: 'https://www.vitawake.co.uk/',
    visitShort: 'vitawake.co.uk',
  },

  /* ------------------------------------------------------ Landing pages */
  {
    name: 'Penmark',
    cat: 'lp',
    label: 'App Landing Page',
    desc: 'Landing page for a timetable and course-management app for university students.',
    tools: 'Nuxt, Vue.js, App Store Links',
    image: shot('penmark-jp'),
    liveUrl: 'https://penmark.jp/',
    visitShort: 'penmark.jp',
  },
  {
    name: 'Kikumasamune KAHO',
    cat: 'lp',
    label: 'Product Page',
    desc: 'Brand page for a flagship junmai daiginjo sake, built around rich visuals and storytelling.',
    tools: 'Craft CMS, JavaScript, Animation',
    image: '',
    liveUrl: 'https://www.kikumasamune.co.jp/products/kaho/',
    visitShort: 'KAHO page',
  },
  {
    name: 'Yaohiko Isshou Mochi',
    cat: 'lp',
    label: 'Campaign LP',
    desc: 'Campaign landing page for a traditional first-birthday rice-cake celebration offered by a long-established Nagoya caterer.',
    tools: 'HTML/CSS, JavaScript, Animation',
    image: '',
    liveUrl: 'https://www.yaohiko.co.jp/isshoumochi/',
    visitShort: 'Isshou Mochi LP',
  },
  {
    name: 'Ebisu Kubono Eye Clinic',
    cat: 'lp',
    label: 'Clinic LP',
    desc: 'Website and landing page for a newly opened eye clinic in Shibuya offering general care and cataract surgery.',
    tools: 'WordPress, PHP, AIOSEO',
    image: shot('ebisu-ganka-com'),
    liveUrl: 'https://www.ebisu-ganka.com/',
    visitShort: 'ebisu-ganka.com',
  },
  {
    name: 'Gochikuru Now',
    cat: 'lp',
    label: 'LP + kintone',
    desc: 'Landing page for an office lunch delivery service, with kintone on the page for enquiries.',
    tools: 'Astro, kintone, Lead Forms',
    image: shot('gochikurunow-com'),
    liveUrl: 'https://gochikurunow.com/',
    visitShort: 'gochikurunow.com',
  },
  {
    name: 'Kurono Reuse',
    cat: 'lp',
    label: 'STUDIO LP',
    desc: 'Landing page for a used-goods buyback service, designed for an older audience with large type and clear calls to action.',
    tools: 'STUDIO, Nuxt, Vue.js',
    image: shot('cr966-com'),
    liveUrl: 'https://cr966.com/',
    visitShort: 'cr966.com',
  },

  /* ------------------------------------------------ Web apps & systems */
  {
    name: 'STORES',
    cat: 'systems',
    label: 'Commerce Platform',
    desc: 'Store operations platform combining POS, payments, reservations, online shops, and mobile ordering in one account.',
    tools: 'Next.js, React, Payments, Reservations',
    image: shot('stores-jp'),
    liveUrl: 'https://stores.jp/',
    visitShort: 'stores.jp',
  },
  {
    name: 'ielove Cloud',
    cat: 'systems',
    label: 'CRM SaaS',
    desc: 'Cloud business platform for real estate companies, covering customer management and property operations.',
    tools: 'CRM, SaaS, Customer Management',
    image: '',
    liveUrl: 'https://ielove-cloud.jp/',
    visitShort: 'ielove-cloud.jp',
  },
  {
    name: 'SourceNext Theft Protection',
    cat: 'systems',
    label: 'Python System',
    desc: 'Account portal for a device theft-protection service. Behind a login, so only the entry screen is public.',
    tools: 'Python, Authentication, Web Portal',
    image: shot('vsm-sourcenext-com'),
    shareUrl: false,
    visitShort: 'SourceNext portal',
  },
  {
    name: 'moovie',
    cat: 'systems',
    label: 'Python System',
    desc: 'Members-only business web application. Behind a login, so only the entry screen is public.',
    tools: 'Python, Authentication, Web App',
    image: shot('moovie-farmers-s-co-jp'),
    shareUrl: false,
    visitShort: 'moovie',
  },
  {
    name: 'Qiita',
    cat: 'systems',
    label: 'Web Platform',
    desc: 'Knowledge-sharing platform where engineers record and publish programming tips and know-how.',
    tools: 'Web Platform, Search, User Accounts',
    image: shot('qiita-com'),
    liveUrl: 'https://qiita.com/',
    visitShort: 'qiita.com',
  },

  /* -------------------------------------------------------- CMS & no-code */
  {
    name: 'Ishikawa Travel',
    cat: 'cms',
    label: 'Craft CMS',
    desc: 'Official English-language travel guide to Ishikawa Prefecture, covering culture, history, food, and nature.',
    tools: 'Craft CMS, Multilingual, JavaScript',
    image: shot('ishikawatravel-jp-en'),
    liveUrl: 'https://www.ishikawatravel.jp/en/',
    visitShort: 'ishikawatravel.jp',
  },
  {
    name: 'Asakusa Kokono Club',
    cat: 'cms',
    label: 'Craft CMS',
    desc: 'Site for an Asakusa theatre and hotel complex, with performance schedules and entertainment news.',
    tools: 'Craft CMS, JavaScript',
    image: shot('asakusa-kokono-com'),
    liveUrl: 'https://asakusa-kokono.com/',
    visitShort: 'asakusa-kokono.com',
  },
  {
    name: 'The Annupuri Lodge Niseko',
    cat: 'cms',
    label: 'Craft CMS',
    desc: 'Accommodation site for a ski lodge beside the Annupuri gondola in Niseko, with rooms, dining, and booking.',
    tools: 'Craft CMS, jQuery, Booking',
    image: shot('annupurilodge-com'),
    liveUrl: 'https://annupurilodge.com/',
    visitShort: 'annupurilodge.com',
  },
  {
    name: 'Dmed',
    cat: 'cms',
    label: 'Craft CMS',
    desc: 'Product site for a collaborative authoring and editing platform for scientific writing.',
    tools: 'Craft CMS, JavaScript',
    image: shot('dmccorp-co-jp'),
    liveUrl: 'https://dmccorp.co.jp/',
    visitShort: 'dmccorp.co.jp',
  },
  {
    name: 'Itagaki–Shitanda Laboratory',
    cat: 'cms',
    label: 'Wix',
    desc: 'Bilingual website for an electroanalytical chemistry lab at Tokyo University of Science.',
    tools: 'Wix, Multilingual',
    image: shot('islab-ca-noda-tus-ac-jp'),
    liveUrl: 'https://www.islab.ca.noda.tus.ac.jp/?lang=en',
    visitShort: 'Lab site',
  },
  {
    name: 'POYL Osteopathic Clinic',
    cat: 'cms',
    label: 'Wix',
    desc: 'Website for an osteopathic and acupuncture clinic in Setagaya, with online booking.',
    tools: 'Wix, Online Booking',
    image: shot('poyl-net'),
    liveUrl: 'https://www.poyl.net/',
    visitShort: 'poyl.net',
  },
  {
    name: 'ALIVE Hair Salon',
    cat: 'cms',
    label: 'Wegeey',
    desc: 'Website for a hair salon in Harajuku and Kichijoji known for balayage and highlight colouring.',
    tools: 'Wegeey, jQuery',
    image: shot('alive-hair-com'),
    liveUrl: 'http://www.alive-hair.com/',
    visitShort: 'alive-hair.com',
  },
  {
    name: 'Lacab.hair',
    cat: 'cms',
    label: 'Wegeey',
    desc: 'Website for a private hair salon in Moriyama, Nagoya, with a kids’ space and head spa menu.',
    tools: 'Wegeey, jQuery',
    image: shot('lacabhair-com'),
    liveUrl: 'https://lacabhair.com/',
    visitShort: 'lacabhair.com',
  },

  /* ---------------------------------------------------------- Web3 */
  {
    name: 'Famous Fox Federation',
    cat: 'web3',
    label: 'Solana NFT',
    desc: 'Solana NFT collection of 7,777 algorithmically generated foxes, with community tools, raffles, and missions.',
    tools: 'Solana, NFT, Web3',
    image: shot('famousfoxes-com'),
    liveUrl: 'https://famousfoxes.com/',
    visitShort: 'famousfoxes.com',
  },
  {
    name: 'Treedefi',
    cat: 'web3',
    label: 'DeFi Platform',
    desc: 'DeFi platform aimed at the ESG crypto space, with exchange, tools, and NFT sections.',
    tools: 'Solidity, DeFi, ERC20, Web3.js',
    image: shot('treedefi-com'),
    liveUrl: 'https://treedefi.com/',
    visitShort: 'treedefi.com',
  },

  /* ------------------------------------------------------ Apps & games */
  {
    name: 'NOGIKOI',
    cat: 'apps',
    label: 'Game App Site',
    desc: 'Official site for the Nogizaka46 romance game app, with member photos, special videos, and app store downloads.',
    tools: 'PHP, jQuery, App Store Links',
    image: shot('nogikoi-jp'),
    liveUrl: 'https://nogikoi.jp/',
    visitShort: 'nogikoi.jp',
  },
  {
    name: 'unityroom',
    cat: 'apps',
    label: 'Game Platform',
    desc: 'Free browser game platform hosting tens of thousands of games made with Unity, with daily rankings.',
    tools: 'Unity, WebGL, Game Hosting',
    image: shot('unityroom-com'),
    liveUrl: 'https://unityroom.com/',
    visitShort: 'unityroom.com',
  },
];
